# Series Object

# Introducing Pandas Objects

In [6]:
pip install pandas
pip install matplotlib
pip install seaborn

SyntaxError: invalid syntax (2808890050.py, line 1)

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\aarin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

## The Pandas Series Object

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a','b','c','d'])

In [ ]:
data['c']

0.75

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['2','5','3','7'])

In [ ]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['pata','peta','pita','pota'])

In [ ]:
data

pata    0.25
peta    0.50
pita    0.75
pota    1.00
dtype: float64

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [3, 7, 1, 9])

In [ ]:
data

3    0.25
7    0.50
1    0.75
9    1.00
dtype: float64

In [ ]:
data.index.dtype

dtype('O')

In [2]:
population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}

In [3]:
population = pd.Series(population_dict)

In [ ]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['California']

38332521

In [ ]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
data = pd.Series(5, index = [100, 200, 300])

In [ ]:
data

100    5
200    5
300    5
dtype: int64

In [ ]:
data = pd.Series({2: 'a', 1: 'c', 3: 'b'})

In [ ]:
data.sort_values

<bound method Series.sort_values of 2    a
1    c
3    b
dtype: object>

In [ ]:
data = pd.Series({1: 3, 5: 2, 3: 4, 2: 1, 4: 5})

In [ ]:
data.sort_index()

1    3
2    1
3    4
4    5
5    2
dtype: int64

In [ ]:
data.sort_values()

2    1
5    2
1    3
3    4
4    5
dtype: int64

In [ ]:
population.sort_index()

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [ ]:
population.sort_values(ascending=False)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [4]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [5]:
area = pd.Series(area_dict)

In [ ]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

## The Pandas DataFrame Object

In [6]:
states = pd.DataFrame({'population': population, 'area': area})

In [7]:
states['density'] = states['population']/states['area']

In [ ]:
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area', 'density'], dtype='object')

In [ ]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [8]:
data = [{'a': i, 'b': 2*i} for i in range(3)]

In [10]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [11]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [12]:
pd.DataFrame(np.random.rand(3,2), columns = ['foo', 'bar'], index = ['a', 'b', 'c'])

foo       bar
a  0.479523  0.488398
b  0.724599  0.599023
c  0.785081  0.756756

In [13]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])

In [14]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [15]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [20]:
ind = pd.Index([2,3,5,7,11])

In [22]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [23]:
list = [i for i in range(20)]

In [30]:
list[:20:4]

[0, 4, 8, 12, 16]

In [31]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [33]:
inda = pd.Index([1,3,5,7,9])
indb = pd.Index([2,3,5,7,11])

In [34]:
inda & indb

Int64Index([3, 5, 7], dtype='int64')

In [35]:
inda | indb

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [36]:
inda ^ indb

Int64Index([1, 2, 9, 11], dtype='int64')

In [37]:
list1 = [1,3,5,7,9]
list2 = [2,3,5,7,11]

In [39]:
dict1 = {1,3,5,7,9}
dict2 = {2,3,5,7,11}

In [40]:
dict1 & dict2

{3, 5, 7}

# Data Indexing and Selection

## Data Selection in Series

In [41]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a','b','c','d'])

In [42]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [43]:
'a' in data

True

In [45]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [48]:
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [56]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [57]:
data['e'] = 1.25

In [58]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [59]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [60]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [61]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [62]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

## Data Selection in DataFrame

In [63]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [64]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [65]:
data = pd.DataFrame({'area': area, 'population': population})

In [67]:
data['density'] = data['population']/data['area']

In [69]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [74]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [75]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [76]:
data.T

California         Texas  ...       Florida      Illinois
area        4.239670e+05  6.956620e+05  ...  1.703120e+05  1.499950e+05
population  3.833252e+07  2.644819e+07  ...  1.955286e+07  1.288214e+07
density     9.041393e+01  3.801874e+01  ...  1.148061e+02  8.588376e+01

[3 rows x 5 columns]

In [77]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [79]:
data.sort_index()

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

# Operating on Data in Pandas